-- LYNX :: settings
--
-- Every knob LYNX exposes lives here. These are DEFAULTS.
--
-- Do NOT edit this file. It is LYNX-owned and `git pull` will overwrite it.
-- Change these from ~/.config/hypr/hyprland.lua instead:
--
--     local s = require("hypr.settings")
--     s.terminal = "alacritty"
--     s.gaps_in  = 2
--     require("hypr.core")          -- core reads whatever you set above
--
-- That works because Lua caches modules: `require` hands you the same table
-- core will later read from. Set values BEFORE requiring core, or core will
-- have already used the defaults.

local s = {}

-- ─── Programs ──────────────────────────────────────────────────────────────
s.terminal = "kitty"   -- also exported as $TERMINAL (see env.lua)

-- ─── Where LYNX lives ──────────────────────────────────────────────────────
-- LYNX calls its own scripts (bin/lx) by absolute path, so nothing depends on
-- ~/.local/bin being on Hyprland's PATH -- which it often isn't when you start
-- Hyprland from a TTY. Must point at the same repo as the package.path line
-- in your ~/.config/hypr/hyprland.lua.
s.lynx_dir = (os.getenv("HOME") or "") .. "/dotfiles/lynx"

-- ─── Bar ───────────────────────────────────────────────────────────────────
-- false = don't start Waybar at login, and don't create the bar keybinds.
s.bar = true

-- ─── Launcher ──────────────────────────────────────────────────────────────
-- false = don't create the launcher keybinds (SUPER+Space, SUPER+Tab).
s.launcher = true

-- ─── Notifications ─────────────────────────────────────────────────────────
-- false = LYNX doesn't start swaync at login or create its keybinds.
-- swaync can still start on its own when an app sends a notification
-- (D-Bus activation). To stop that too:  systemctl --user mask swaync
s.notifications = true

-- ─── Wallpaper ─────────────────────────────────────────────────────────────
-- false = LYNX doesn't start hyprpaper or create the wallpaper keybinds.
s.wallpaper = true

-- ─── Lock & idle ───────────────────────────────────────────────────────────
-- s.lock = the lock keybind (SUPER + ALT + L).
-- s.idle = hypridle: locks after inactivity and before the machine sleeps.
--          The timeouts themselves live in ~/.config/hypr/hypridle.conf.
s.lock = true
s.idle = true

-- ─── Theme ─────────────────────────────────────────────────────────────────
-- true  = colors follow your wallpaper (matugen): borders, bar, launcher,
--         notifications, lock screen, kitty.
-- false = LYNX's fixed fallback palette everywhere. After switching this off,
--         run `lx theme reset` once. Dark/light and the color style are set
--         with `lx theme mode` and `lx theme scheme`, not here.
s.theme = true

-- ─── Screenshots, clipboard, power menu ────────────────────────────────────
-- false = that feature's keybinds aren't created. For the clipboard, it also
-- means history isn't recorded at login (then run `lx clipboard wipe`).
s.screenshots = true
s.clipboard   = true
s.power_menu  = true

-- ─── Modifier ──────────────────────────────────────────────────────────────
s.mod = "SUPER"

-- ─── Layout & spacing ──────────────────────────────────────────────────────
s.layout      = "dwindle"
s.gaps_in     = 5
s.gaps_out    = 12
s.border_size = 2
s.rounding    = 10

-- ─── Input ─────────────────────────────────────────────────────────────────
s.kb_layout      = "us"
s.kb_variant     = ""
s.kb_options     = ""
s.follow_mouse   = 1
s.sensitivity    = 0      -- -1.0 .. 1.0, 0 = unmodified
s.natural_scroll = false

-- ─── Cursor ────────────────────────────────────────────────────────────────
s.cursor_size = 24

-- ─── Effects ───────────────────────────────────────────────────────────────
-- Turning blur off is the single biggest GPU win available here. If Hyprland
-- ever feels sluggish, set s.blur = false from your hyprland.lua first.
s.blur        = true
s.blur_size   = 3
s.blur_passes = 1
s.shadow      = true
s.animations  = true

-- ─── Fallback palette ──────────────────────────────────────────────────────
-- Used ONLY until the theming piece lands. From then on, matugen writes
-- ~/.cache/lynx/colors.lua and these values are ignored. See looks.lua.
s.colors = {
    active_border   = "rgba(89b4faee)",
    inactive_border = "rgba(45475aaa)",
    shadow          = 0xee1a1a1a,
}

return s
